### ISSUE TITLE
Wrong indentation of exported object field in type definition

### ISSUE THREAD

**Issue by AmaiKinono** [nim-lang/nim-mode#234]
Conforming Bugs
===============

Please tell us below:

- [ ] basic information
   - OS name: GNU/Linux
   - Versions: Emacs 27.1, Nim compiler 1.4.2, and nimsuggest 1.4.2
- [x] Are you using latest version of nim-mode? 
      Yes.
- [ ] Are there message related to nim-mode in `*Messages*` buffer?
      No.
- [x] Did you read README.md?
      Yes.
- [ ] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc)
      No.

And describe your problem:

Enter this in `nim-mode`:

```nim
type
  NewType* = object
    field1*: string
    field2*: string
```

Mark them, call `indent-region`. Now it becomes:

```nim
type
  NewType* = object
    field1*: string
          field2*: string
```

I believe it's a problem related to the SMIE grammar, but I don't have enough knowledge on SMIE and parser/grammar things to fix this.

**Comment by cctor** [comment]
I fixed this by change the `nim-smie.el`.

## The problem
1.  `nim-smie--object` function captures the pcase `` `(,_ . "object") `` in function `nim-mode-smie-rules`
2.  but in `nim-smie--object`, it only processed `:before` and `:after`
3.  so (maybe) the indentation rule fallbacks to some strange rule (I'm not familiar with SMIE)

## How to solve
1. in file `nim-smie.el`
2. in function `nim-smie--object`
3. add the default case to `cl-case`
4. `(t (current-indentation))`

## todo
1. Should we process the default case more precisely?
